---

  - name: 'Get Record ID'
    uri: url="http://api.plos.org/search?q=title:DNA" return_content=yes
    register: get_record_id


  - name: 'Display Record ID Property'
    debug: 
      msg: "ID: {{ (get_record_id.content|from_json)['response']['docs'][0]['id'] }}"

  - name: 'Display Record ID Property another way'
    debug:
      msg: "ID: {{ get_record_id.json.response.docs[0].id }}"


  - name: 'Store Result as a String'
    set_fact: 
      "json_result": "{{ get_record_id.json.response.docs[0] }}"

  - name: 'Display Result from a Fact'
    debug:
      msg: "Record ID: {{ json_result.id.split('.')[-1] }}"

