---

  - name: 'Get JSON result'
    uri: url="http://api.plos.org/search?q=title:DNA" return_content=yes
    register: get_json_result


  - name: "Display the first JSON object's ID property"
    debug: 
      msg: "ID: {{ (get_json_result.content|from_json)['response']['docs'][0]['id'] }}"

  - name: "Display the first JSON object's ID property another way"
    debug:
      msg: "ID: {{ get_json_result.json.response.docs[0].id }}"


  - name: "Store the first JSON object as a Ansible fact"
    set_fact: 
      "json_result": "{{ get_json_result.json.response.docs[0] }}"

  - name: "Parse and display the first JSON object ID number from the Ansible fact"
    debug:
      msg: "Record ID: {{ json_result.id.split('.')[-1] }}"


